### ISSUE TITLE
Test Examples available?

### ISSUE THREAD

**Issue by bxc237** [ori-drs/pronto#16]
Are there any rosbag files to test this new ROS pronto like the old one with lcm logs? THX!

**Comment by mcamurri** [comment]
Hi @bxc237, 
I had plans to release a complete example with a open-source robot URDF, but there is not a release date yet.

Some components for HyQ and ANYmal were proprietary, so I have to remove the proprietary parts first to release it.

I'll let you know when it's done!

**Comment by mcamurri** [comment]
Hi @bxc237 , I've finally completed a full ANYmal example with a rosbag. 
You can find it here:
https://github.com/ori-drs/pronto_anymal_example

Hope that you find it useful.

**Comment by bxc237** [comment]
Thank you very much!!
